(ns roman-numerals)

(defn numerals [n]
  (defn helper [m acc]
    (if (or (<= m 0)
            (>  m 3000))
      acc
      (if (>= m 1000)
        (recur (- m 1000) (str acc "M"))
        (if (>= m 900)
          (recur (- m 900) (str acc "CM"))
          (if (>= m 500)
            (recur (- m 500) (str acc "D"))
            (if (>= m 400)
              (recur (- m 400) (str acc "CD"))
              (if (>= m 100)
                (recur (- m 100) (str acc "C"))
                (if (>= m 90)
                  (recur (- m 90) (str acc "XC"))
                  (if (>= m 50)
                    (recur (- m 50) (str acc "L"))
                    (if (>= m 40)
                      (recur (- m 40) (str acc "XL"))
                      (if (>= m 10)
                        (recur (- m 10) (str acc "X"))
                        (if (>= m 9)
                          (recur (- m 9) (str acc "IX"))
                          (if (>= m 5)
                            (recur (- m 5) (str acc "V"))
                            (if (>= m 4)
                              (recur (- m 4) (str acc "IV"))
                              (if (>= m 1)
                                (recur (- m 1) (str acc "I")))))))))))))))))
  (helper n ""))
